apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: develop
spec:
  selector:
    app: neo4j
  type: NodePort
  ports:
    - protocol: TCP
      name: web
      port: 7474
      targetPort: 7474
    - protocol: TCP
      name: bolt
      port: 7687
      targetPort: 7687
