apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j-statefulset
  namespace: develop
  labels:
    app: graph-db
spec:
  serviceName: linchfin-neo4j
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j
        ports:
        - containerPort: 7474
          hostPort: 7474
        - containerPort: 7687
          hostPort: 7687